// Generated by Wrangler
// Cloudflare Workers 环境绑定类型声明
/// <reference types="@cloudflare/workers-types" />
interface Env {
  R2_BUCKET: R2Bucket;
  KV_META: KVNamespace;
  ADMIN_PASSWORD?: string;  // 可选 — 未设置时显示配置提示
  JWT_SECRET?: string;      // 可选 — 未设置时自动生成并存储到 KV
  SITE_URL?: string;        // 可选 — 未设置时自动从请求 URL 检测
  ASSETS: Fetcher;
}
